version: "3"

services:
  db:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres

  redis:
    image: redis:4.0-alpine
    ports:
      - "6379:6379"
volumes:
  postgres-data:
